dataset:
  name: iu_chestxray
  root: "/kaggle/input/chest-xrays-indiana-university"
  images_dir: "images/images_normalized"
  split: "all"
preprocess:
  size: [224, 224]
  mode: "gray"
  use_clahe: true
runtime:
  batch_size: 8
  num_workers: 4
  device: "auto"
logging:
  out_dir: "/kaggle/working/results/projection"
