dataset:
  name: iu_chestxray
  base_dir: "D:/MedVLMPhase1/data/chestxray_iu"
  images_subdir: "images/images_normalized"
  reports_csv: "indiana_reports.csv"
  projections_csv: "indiana_projections.csv"

loader:
  img_size: 224
  batch_size: 32
  num_workers: 2
  grayscale: true

output:
  dir: "D:/MedVLMPhase1/outputs"

logging:
  level: INFO
  save_metrics: true
  save_plots: true

runtime:
  device: "auto"
